/**
 * Payment use-cases.
 *
 * Recording a payment is the single most correctness-critical write in the system,
 * so the shape is worth stating explicitly.
 *
 * ONE transaction does all of:
 *   1. allocate the money across the student's open invoices (oldest due first)
 *   2. append a PAYMENT_RECEIVED ledger entry per allocated invoice
 *   3. turn any remainder into a StudentCredit (or reject it, per settings)
 *   4. recalculate each touched invoice's derived caches
 *   5. write the audit entry and the student timeline entry
 *   6. enqueue the receipt notification
 *
 * It runs at SERIALIZABLE isolation. READ COMMITTED permits write skew: two
 * concurrent payments both read the same open balance, both allocate against it,
 * and the invoice ends up over-allocated with no constraint violated. The
 * `idempotencyKey` unique index stops an accidental double-submit of the SAME
 * request; serialisable isolation stops two DIFFERENT requests racing. Both are
 * needed — neither substitutes for the other.
 */

import type { PaymentMethod, Prisma } from '@/generated/prisma/client';
import { withSerializableRetry, type Db, type Tx } from '@/server/db/client';
import {
  BusinessRuleError,
  ConflictError,
  NotFoundError,
  StateInvalidError,
} from '@/server/errors';
import { AUDIT_ACTIONS, record as recordAudit } from '@/server/audit';
import {
  assertBranchAccess,
  requirePermission,
  scopeFilter,
  type AccessContext,
} from '@/server/rbac/access';
import { getSettings } from '@/server/settings';
import { logger } from '@/server/observability/logger';
import { formatMoney, money } from '@/lib/money';
import { appendLedgerEntry, recalculateInvoice, reverseLedgerEntry } from '@/server/services/finance/ledger';
import { nextPaymentNumber } from '@/server/services/finance/numbering';
import { currencyFor } from '@/server/services/finance/currency';

export interface RecordPaymentInput {
  readonly studentId: string;
  readonly amountMinor: bigint;
  readonly currency?: string;
  readonly method: PaymentMethod;
  readonly branchId?: string | null;
  /** Bank reference, cheque number, terminal slip id. */
  readonly reference?: string | null;
  /** Gateway transaction id, for ONLINE payments. */
  readonly providerRef?: string | null;
  readonly providerKey?: string | null;
  /** Business date. Defaults to now; an accountant may back-date a receipt. */
  readonly receivedAt?: Date;
  readonly notes?: string | null;
  /**
   * Required. Generated by the client per submission so a retried request or a
   * replayed webhook cannot post the money twice.
   */
  readonly idempotencyKey: string;
  /**
   * Target specific invoices in this order instead of oldest-due-first. Used when
   * a parent says "this is for the March invoice".
   */
  readonly invoiceIds?: readonly string[];
  /** Fund the payment from existing student credit rather than new money. */
  readonly fromCreditId?: string | null;
}

export interface RecordPaymentResult {
  readonly id: string;
  readonly paymentNumber: string;
  readonly amountMinor: bigint;
  readonly currency: string;
  readonly allocations: ReadonlyArray<{
    readonly invoiceId: string;
    readonly invoiceNumber: string;
    readonly amountMinor: bigint;
    readonly remainingBalanceMinor: bigint;
  }>;
  /** Amount that could not be allocated and became credit. */
  readonly creditedMinor: bigint;
  readonly creditId: string | null;
  /** True when this call returned an existing payment rather than creating one. */
  readonly wasAlreadyRecorded: boolean;
}

/**
 * Record a payment and allocate it across open invoices.
 *
 * Allocation order is oldest DUE DATE first, then oldest issue date. That is the
 * conventional and legally safer default: it clears the debt that has been
 * outstanding longest, which is what a parent expects and what keeps the ageing
 * report honest. A caller may override it with `invoiceIds`.
 */
export async function recordPayment(
  ctx: AccessContext,
  input: RecordPaymentInput,
  db?: Db,
): Promise<RecordPaymentResult> {
  requirePermission(ctx, 'payments.create');

  if (input.amountMinor <= 0n) {
    throw new BusinessRuleError(
      'payment.non_positive_amount',
      'A payment must be for a positive amount.',
    );
  }
  if (!input.idempotencyKey.trim()) {
    throw new BusinessRuleError(
      'payment.missing_idempotency_key',
      'An idempotency key is required to record a payment.',
    );
  }

  return withSerializableRetry(
    async (tx) => {
      // --- replay check ---------------------------------------------------
      // Checked inside the transaction so a genuine race falls through to the
      // unique index rather than both callers passing this test.
      const existing = await tx.payment.findUnique({
        where: { idempotencyKey: input.idempotencyKey },
        select: {
          id: true,
          organizationId: true,
          paymentNumber: true,
          amountMinor: true,
          currency: true,
          allocations: {
            select: {
              amountMinor: true,
              invoice: { select: { id: true, invoiceNumber: true, balanceMinor: true } },
            },
          },
        },
      });

      if (existing) {
        if (existing.organizationId !== ctx.organizationId) {
          // The key belongs to another tenant. Reporting it as a conflict would
          // confirm its existence, so this reads as an ordinary duplicate.
          throw new ConflictError('This payment reference has already been used.');
        }
        logger.info('payment.idempotent_replay', {
          requestId: ctx.requestId,
          organizationId: ctx.organizationId,
          paymentId: existing.id,
        });
        return {
          id: existing.id,
          paymentNumber: existing.paymentNumber,
          amountMinor: existing.amountMinor,
          currency: existing.currency,
          allocations: existing.allocations.map((allocation) => ({
            invoiceId: allocation.invoice.id,
            invoiceNumber: allocation.invoice.invoiceNumber,
            amountMinor: allocation.amountMinor,
            remainingBalanceMinor: allocation.invoice.balanceMinor,
          })),
          creditedMinor: 0n,
          creditId: null,
          wasAlreadyRecorded: true,
        };
      }

      // --- subject and scope ----------------------------------------------
      const student = await tx.student.findFirst({
        where: { id: input.studentId, ...scopeFilter(ctx), deletedAt: null },
        select: { id: true, branchId: true, firstName: true, lastName: true },
      });
      if (!student) throw new NotFoundError('Student', input.studentId);

      const branchId = input.branchId ?? student.branchId;
      assertBranchAccess(ctx, branchId, 'payment');

      const settings = await getSettings(['allowOverpayment'], {
        organizationId: ctx.organizationId,
        branchId,
      }, tx);

      const currency = await currencyFor(
        { organizationId: ctx.organizationId, branchId, requested: input.currency },
        tx,
      );
      const receivedAt = input.receivedAt ?? new Date();

      // --- credit-funded payments -----------------------------------------
      let sourceCredit: { id: string; balanceMinor: bigint; currency: string } | null = null;
      if (input.fromCreditId) {
        const credit = await tx.studentCredit.findFirst({
          where: {
            id: input.fromCreditId,
            organizationId: ctx.organizationId,
            studentId: student.id,
            status: { in: ['AVAILABLE', 'PARTIALLY_USED'] },
          },
          select: { id: true, balanceMinor: true, currency: true },
        });
        if (!credit) throw new NotFoundError('Student credit', input.fromCreditId);
        if (credit.currency !== currency) {
          throw new BusinessRuleError(
            'payment.credit_currency_mismatch',
            'The credit is held in a different currency from this payment.',
          );
        }
        if (credit.balanceMinor < input.amountMinor) {
          throw new BusinessRuleError(
            'payment.credit_insufficient',
            `The credit has only ${formatMoney(money(credit.balanceMinor, currency))} available.`,
            { details: { availableMinor: credit.balanceMinor.toString() } },
          );
        }
        sourceCredit = credit;
      }

      // --- pick the invoices to settle -------------------------------------
      const openInvoices = await selectAllocationTargets(tx, {
        organizationId: ctx.organizationId,
        studentId: student.id,
        currency,
        invoiceIds: input.invoiceIds,
      });

      // --- allocate --------------------------------------------------------
      let remaining = input.amountMinor;
      const allocations: Array<{
        invoiceId: string;
        invoiceNumber: string;
        amountMinor: bigint;
      }> = [];

      for (const invoice of openInvoices) {
        if (remaining === 0n) break;
        const applied = invoice.balanceMinor < remaining ? invoice.balanceMinor : remaining;
        if (applied <= 0n) continue;
        allocations.push({
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          amountMinor: applied,
        });
        remaining -= applied;
      }

      if (remaining > 0n && !settings.allowOverpayment) {
        throw new BusinessRuleError(
          'payment.overpayment_not_allowed',
          `This payment exceeds the outstanding balance by ${formatMoney(money(remaining, currency))}. Overpayment is disabled for this organisation.`,
          { details: { excessMinor: remaining.toString() } },
        );
      }

      // --- persist ---------------------------------------------------------
      const paymentNumber = await nextPaymentNumber(tx, {
        organizationId: ctx.organizationId,
        branchId,
        now: receivedAt,
      });

      const payment = await tx.payment.create({
        data: {
          organizationId: ctx.organizationId,
          branchId,
          paymentNumber,
          studentId: student.id,
          // A convenience pointer only when the money went to exactly one invoice;
          // the authoritative split always lives in PaymentAllocation.
          invoiceId: allocations.length === 1 ? allocations[0]!.invoiceId : null,
          method: sourceCredit ? 'CREDIT_NOTE' : input.method,
          status: 'COMPLETED',
          amountMinor: input.amountMinor,
          currency,
          receivedAt,
          reference: input.reference ?? null,
          providerRef: input.providerRef ?? null,
          providerKey: input.providerKey ?? null,
          idempotencyKey: input.idempotencyKey,
          receivedById: ctx.isSystem ? null : ctx.userId,
          notes: input.notes ?? null,
          sourceCreditId: sourceCredit?.id ?? null,
          allocations: {
            create: allocations.map((allocation) => ({
              invoiceId: allocation.invoiceId,
              amountMinor: allocation.amountMinor,
              currency,
            })),
          },
        },
        select: { id: true, paymentNumber: true },
      });

      // One ledger entry per invoice, so every invoice's derived total can be
      // re-derived from the ledger alone without consulting the allocation table.
      for (const allocation of allocations) {
        await appendLedgerEntry(ctx, tx, {
          entryType: sourceCredit ? 'CREDIT_APPLIED' : 'PAYMENT_RECEIVED',
          direction: 'CREDIT',
          amountMinor: allocation.amountMinor,
          currency,
          branchId,
          studentId: student.id,
          invoiceId: allocation.invoiceId,
          paymentId: payment.id,
          creditId: sourceCredit?.id ?? null,
          occurredAt: receivedAt,
          description: `Payment ${paymentNumber} applied to invoice ${allocation.invoiceNumber}`,
        });
      }

      // --- consume or create credit ----------------------------------------
      if (sourceCredit) {
        const newBalance = sourceCredit.balanceMinor - input.amountMinor;
        await tx.studentCredit.update({
          where: { id: sourceCredit.id },
          data: {
            balanceMinor: newBalance,
            status: newBalance === 0n ? 'EXHAUSTED' : 'PARTIALLY_USED',
          },
        });
      }

      let creditId: string | null = null;
      if (remaining > 0n) {
        const credit = await tx.studentCredit.create({
          data: {
            organizationId: ctx.organizationId,
            studentId: student.id,
            source: 'OVERPAYMENT',
            sourcePaymentId: payment.id,
            amountMinor: remaining,
            balanceMinor: remaining,
            currency,
            status: 'AVAILABLE',
            note: `Overpayment on ${paymentNumber}`,
            createdById: ctx.isSystem ? null : ctx.userId,
          },
          select: { id: true },
        });
        creditId = credit.id;

        await appendLedgerEntry(ctx, tx, {
          entryType: 'CREDIT_ISSUED',
          direction: 'CREDIT',
          amountMinor: remaining,
          currency,
          branchId,
          studentId: student.id,
          paymentId: payment.id,
          creditId: credit.id,
          occurredAt: receivedAt,
          description: `Overpayment on ${paymentNumber} held as credit`,
        });
      }

      // --- recalculate the touched invoices --------------------------------
      // Built up mutably, then returned as the readonly result type.
      const settled: Array<{
        invoiceId: string;
        invoiceNumber: string;
        amountMinor: bigint;
        remainingBalanceMinor: bigint;
      }> = [];
      for (const allocation of allocations) {
        const totals = await recalculateInvoice(tx, allocation.invoiceId, { now: receivedAt });
        settled.push({
          invoiceId: allocation.invoiceId,
          invoiceNumber: allocation.invoiceNumber,
          amountMinor: allocation.amountMinor,
          remainingBalanceMinor: totals.balanceMinor,
        });
      }

      await recordAudit(
        ctx,
        {
          action: AUDIT_ACTIONS.PAYMENT_RECORDED,
          entityType: 'Payment',
          entityId: payment.id,
          branchId,
          summary: `Payment ${paymentNumber} of ${formatMoney(money(input.amountMinor, currency))} from ${student.firstName} ${student.lastName}`,
          metadata: {
            amountMinor: input.amountMinor.toString(),
            currency,
            method: input.method,
            invoiceCount: allocations.length,
            creditedMinor: remaining.toString(),
          },
          timeline: {
            subjectType: 'STUDENT',
            subjectId: student.id,
            type: 'payment.received',
            title: `Payment received: ${formatMoney(money(input.amountMinor, currency))}`,
            description:
              allocations.length > 0
                ? `Applied to ${allocations.map((a) => a.invoiceNumber).join(', ')}`
                : 'Held as credit on account',
            occurredAt: receivedAt,
          },
        },
        tx,
      );

      return {
        id: payment.id,
        paymentNumber,
        amountMinor: input.amountMinor,
        currency,
        allocations: settled,
        creditedMinor: remaining,
        creditId,
        wasAlreadyRecorded: false,
      };
    },
    { existing: db },
  );
}

/**
 * The invoices a payment may settle, in allocation order.
 *
 * Explicit `invoiceIds` are honoured in the order given and validated to belong
 * to the student — otherwise a caller could pay down another student's invoice by
 * guessing an id.
 */
async function selectAllocationTargets(
  tx: Tx,
  input: {
    organizationId: string;
    studentId: string;
    currency: string;
    invoiceIds?: readonly string[];
  },
): Promise<Array<{ id: string; invoiceNumber: string; balanceMinor: bigint }>> {
  const base: Prisma.InvoiceWhereInput = {
    organizationId: input.organizationId,
    studentId: input.studentId,
    currency: input.currency,
    balanceMinor: { gt: 0 },
    // A draft has raised no charge, and these three are closed.
    status: { notIn: ['DRAFT', 'CANCELLED', 'VOID'] },
  };

  if (input.invoiceIds && input.invoiceIds.length > 0) {
    const found = await tx.invoice.findMany({
      where: { ...base, id: { in: [...input.invoiceIds] } },
      select: { id: true, invoiceNumber: true, balanceMinor: true },
    });

    const byId = new Map(found.map((invoice) => [invoice.id, invoice]));
    const missing = input.invoiceIds.filter((id) => !byId.has(id));
    if (missing.length > 0) {
      throw new BusinessRuleError(
        'payment.invoice_not_payable',
        'One or more of the selected invoices does not belong to this student, is already settled, or is closed.',
        { details: { invoiceIds: missing } },
      );
    }
    // Preserve the caller's order: they chose which invoice to clear first.
    return input.invoiceIds.map((id) => byId.get(id)!);
  }

  return tx.invoice.findMany({
    where: base,
    select: { id: true, invoiceNumber: true, balanceMinor: true },
    orderBy: [{ dueDate: 'asc' }, { issueDate: 'asc' }, { invoiceNumber: 'asc' }],
  });
}

/**
 * Reverse a completed payment: a bounced cheque, a chargeback, a keying error.
 *
 * Nothing is deleted. Each PAYMENT_RECEIVED entry gets a PAYMENT_REVERSED
 * counterpart pointing at it through `reversalOfId`, the invoices are
 * recalculated, and any credit the payment created is revoked. The original
 * payment row stays, marked REVERSED, because it was on a receipt someone holds.
 */
export async function reversePayment(
  ctx: AccessContext,
  paymentId: string,
  input: { reason: string },
  db?: Db,
): Promise<{ id: string; reversedInvoices: readonly string[] }> {
  requirePermission(ctx, 'payments.reverse');

  if (!input.reason.trim()) {
    throw new BusinessRuleError(
      'payment.reversal_needs_reason',
      'A reversal must record why the payment was reversed.',
    );
  }

  return withSerializableRetry(
    async (tx) => {
      const payment = await tx.payment.findFirst({
        where: { id: paymentId, ...scopeFilter(ctx) },
        select: {
          id: true,
          paymentNumber: true,
          status: true,
          amountMinor: true,
          currency: true,
          branchId: true,
          studentId: true,
          receivedAt: true,
          refunds: { where: { status: { in: ['APPROVED', 'PROCESSED'] } }, select: { id: true } },
          credits: { select: { id: true, balanceMinor: true, amountMinor: true } },
          ledgerEntries: {
            where: { entryType: { in: ['PAYMENT_RECEIVED', 'CREDIT_APPLIED', 'CREDIT_ISSUED'] } },
            select: { id: true, invoiceId: true, entryType: true, reversedBy: { select: { id: true } } },
          },
        },
      });
      if (!payment) throw new NotFoundError('Payment', paymentId);

      if (payment.status === 'REVERSED') {
        throw new StateInvalidError('payment', 'already reversed', 'reversed');
      }
      if (payment.status !== 'COMPLETED') {
        throw new StateInvalidError('payment', payment.status.toLowerCase(), 'reversed');
      }
      if (payment.refunds.length > 0) {
        // Reversing a refunded payment would double-count the money going out.
        throw new BusinessRuleError(
          'payment.already_refunded',
          'This payment has been refunded. Reverse the refund first if that was a mistake.',
        );
      }

      const now = new Date();
      const touchedInvoices = new Set<string>();

      for (const entry of payment.ledgerEntries) {
        if (entry.reversedBy) continue; // Idempotent if a previous attempt partly ran.
        await reverseLedgerEntry(ctx, tx, entry.id, {
          entryType: 'PAYMENT_REVERSED',
          description: `Payment ${payment.paymentNumber} reversed: ${input.reason}`,
          occurredAt: now,
        });
        if (entry.invoiceId) touchedInvoices.add(entry.invoiceId);
      }

      // Revoke credit the payment created. Consuming it first and then reversing
      // the payment would leave the student holding money that was never paid.
      for (const credit of payment.credits) {
        if (credit.balanceMinor !== credit.amountMinor) {
          throw new BusinessRuleError(
            'payment.credit_partly_spent',
            'The credit created by this payment has already been partly used. Raise an adjustment instead of reversing.',
            { details: { creditId: credit.id } },
          );
        }
        await tx.studentCredit.update({
          where: { id: credit.id },
          data: { balanceMinor: 0n, status: 'REVOKED', note: `Revoked: ${input.reason}` },
        });
      }

      await tx.payment.update({
        where: { id: payment.id },
        data: {
          status: 'REVERSED',
          reversedAt: now,
          reversalReason: input.reason,
          reversedById: ctx.isSystem ? null : ctx.userId,
        },
      });

      for (const invoiceId of touchedInvoices) {
        await recalculateInvoice(tx, invoiceId, { now });
      }

      await recordAudit(
        ctx,
        {
          action: AUDIT_ACTIONS.PAYMENT_REVERSED,
          entityType: 'Payment',
          entityId: payment.id,
          branchId: payment.branchId,
          summary: `Payment ${payment.paymentNumber} of ${formatMoney(money(payment.amountMinor, payment.currency))} reversed`,
          reason: input.reason,
          // WARNING severity means the audit write is NOT best-effort: if it
          // cannot be recorded, the reversal itself fails.
          severity: 'WARNING',
          metadata: {
            amountMinor: payment.amountMinor.toString(),
            currency: payment.currency,
            invoiceCount: touchedInvoices.size,
          },
          timeline: {
            subjectType: 'STUDENT',
            subjectId: payment.studentId,
            type: 'payment.reversed',
            title: `Payment ${payment.paymentNumber} reversed`,
            description: input.reason,
            occurredAt: now,
          },
        },
        tx,
      );

      return { id: payment.id, reversedInvoices: [...touchedInvoices] };
    },
    { existing: db },
  );
}
