import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypeScript from 'eslint-config-next/typescript';

/**
 * ESLint flat config.
 *
 * `eslint-config-next` 16 ships NATIVE flat-config arrays, so they are spread
 * directly. The obvious-looking alternative — wrapping them with
 * `FlatCompat.extends(...)` from `@eslint/eslintrc` — fails here with
 * "Converting circular structure to JSON": the legacy shim tries to validate the
 * modern config, hits the self-referential `plugins.react` object, and then cannot
 * even serialise its own error. The result is a stack trace that mentions nothing
 * about the actual problem, which is why this is written down.
 */
const config = [
  ...nextCoreWebVitals,
  ...nextTypeScript,

  {
    ignores: [
      '.next/**',
      'node_modules/**',
      '.dev-db/**',
      '.storage/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by `prisma generate`; not ours to lint.
      'src/generated/**',
      'next-env.d.ts',
    ],
  },

  {
    rules: {
      // The single most important rule in this codebase: `any` disables every
      // other guarantee the type system provides.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          // Destructuring to drop a field is a deliberate idiom, e.g.
          // `const { passwordHash: _omit, ...safe } = user`.
          ignoreRestSiblings: true,
        },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'no-var': 'error',
      'object-shorthand': ['error', 'properties'],
      // Floating promises are how a transaction silently fails to be awaited.
      'no-return-await': 'off',
      'require-await': 'off',
    },
  },

  {
    // CLI entrypoints and the seed: stdout IS the interface.
    files: ['scripts/**/*.ts', 'prisma/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  {
    // The logger is the one place allowed to reach for the console directly.
    files: ['src/server/observability/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  {
    // Tests assert on shapes that are deliberately wrong, and log diagnostics.
    files: ['tests/**/*.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },
];

export default config;
