/**
 * Concrete lessons: materialising them from the timetable, and the exceptions.
 *
 * A `Lesson` is the dated instance attendance, homework and grades hang off. Two
 * things about this file matter more than the rest:
 *
 * GENERATION IS IDEMPOTENT. `generateLessons` may be run by a cron, by an
 * administrator pressing a button, and by both at once. The unique index on
 * (groupId, startsAt) is what makes that safe rather than merely unlikely: the
 * insert uses `skipDuplicates`, and the run reports created vs skipped instead of
 * failing. Re-running over the same range creates nothing.
 *
 * AN EXCEPTION IS A RECORD, NOT A DELETION. A cancelled lesson keeps its row with
 * a reason; a rescheduled one keeps its identity so the attendance already
 * attached to it does not become an orphan. Nothing here deletes a Lesson.
 */

import type { LessonAttendanceStatus, LessonStatus, Prisma } from '@/generated/prisma/client';
import { prisma, withSerializableRetry, withTransaction, type Db } from '@/server/db/client';
import {
  BusinessRuleError,
  ConflictError,
  ForbiddenError,
  NotFoundError,
  ScheduleConflictError,
  StateInvalidError,
  type ScheduleConflict,
} from '@/server/errors';
import { AUDIT_ACTIONS, diffFields, record as recordAudit } from '@/server/audit';
import {
  can,
  composeReadFilter,
  requirePermission,
  scopeFilter,
  teacherLessonFilter,
  type AccessContext,
} from '@/server/rbac/access';
import { getSettings } from '@/server/settings';
import { logger } from '@/server/observability/logger';
import {
  addDaysToDateOnly,
  dateOnlyToPrismaDate,
  datesMatchingWeekdays,
  dayRangeToInstants,
  formatTime,
  formatWallClock,
  instantToWallClockMinute,
  prismaDateToDateOnly,
  todayIn,
  toIso,
  weekdayOf,
  zonedWallClockToInstant,
  type DateOnly,
  type TimeZone,
} from '@/lib/dates';
import {
  addToLessonConflictIndex,
  findLessonConflictsInIndex,
  indexLessonsForConflicts,
  lessonAsSlotCandidate,
  TIME_FREEING_LESSON_STATUSES,
} from '@/server/services/scheduling/conflicts';
import { assertSlotIsFree, loadGenerableSlots } from '@/server/services/scheduling/slots';
import {
  assertGroupSchedulable,
  assertMinuteWindow,
  MINUTES_IN_DAY,
  resolveResources,
} from '@/server/services/scheduling/resources';

/**
 * The instant a local wall-clock minute falls on.
 *
 * `zonedWallClockToInstant` resolves the offset from the zone database for that
 * particular date, which is the whole point: a class at 09:00 local stays at
 * 09:00 local across a DST transition instead of jumping to 08:00 or 10:00 as it
 * would if lessons were generated by adding fixed durations to a first instant.
 * A window ending at 24:00 is expressed as midnight on the following day, because
 * there is no 24:00 wall clock to convert.
 */
function instantFor(date: DateOnly, minute: number, zone: TimeZone): Date {
  return minute === MINUTES_IN_DAY
    ? zonedWallClockToInstant(addDaysToDateOnly(date, 1), 0, zone)
    : zonedWallClockToInstant(date, minute, zone);
}

/** `${groupId}|${startsAt}` — the shape of the (groupId, startsAt) unique index. */
function lessonKey(groupId: string, startsAt: Date): string {
  return `${groupId}|${startsAt.getTime()}`;
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

export interface GenerateLessonsInput {
  /** Defaults to today in the organisation timezone. */
  readonly fromDate?: DateOnly;
  /** Defaults to the configured horizon; clamped to it when further out. */
  readonly throughDate?: DateOnly;
  readonly branchId?: string | null;
  readonly groupId?: string | null;
  readonly slotId?: string | null;
}

export interface GenerateLessonsResult {
  readonly from: DateOnly;
  readonly to: DateOnly;
  readonly slotsConsidered: number;
  readonly candidates: number;
  readonly created: number;
  /** Already present — the idempotent case, not an error. */
  readonly skippedExisting: number;
  /** Blocked by a teacher, room or group clash with something already booked. */
  readonly skippedConflicting: number;
  /** A sample of the blocking clashes, for an operator to act on. */
  readonly conflicts: readonly ScheduleConflict[];
  readonly clampedToHorizon: boolean;
  readonly horizonWeeks: number;
}

const CONFLICT_SAMPLE_LIMIT = 20;

/**
 * Materialise `Lesson` rows from the active timetable over a date range.
 *
 * A candidate that clashes is SKIPPED and reported, not thrown: aborting a whole
 * term's generation because one room was double-booked by an ad-hoc lesson would
 * leave the timetable half-built, and the operator needs the list of problems
 * rather than the first one.
 */
export async function generateLessons(
  ctx: AccessContext,
  input: GenerateLessonsInput = {},
  db?: Db,
): Promise<GenerateLessonsResult> {
  requirePermission(ctx, 'schedule.generateLessons');

  // READ COMMITTED, unlike the single-write paths. This is a long bulk job that
  // touches most of the term's rows, so Serializable would abort it whenever an
  // administrator happened to save a lesson; and the guard it actually relies on
  // is the (groupId, startsAt) unique index plus `skipDuplicates`, not isolation.
  // Generation reports clashes rather than enforcing them, so a lost race here
  // costs a re-run, not a corrupted timetable.
  return withTransaction(
    async (tx) => {
      const settings = await getSettings(
        ['timezone', 'lessonGenerationHorizonWeeks'],
        { organizationId: ctx.organizationId, branchId: input.branchId ?? null },
        tx,
      );
      const zone = settings.timezone;
      const horizonWeeks = settings.lessonGenerationHorizonWeeks;

      const from = input.fromDate ?? todayIn(zone);
      // The horizon is a hard ceiling, not a default: a caller asking for three
      // years of lessons would otherwise write a million rows nobody reviewed.
      const horizonEnd = addDaysToDateOnly(from, horizonWeeks * 7 - 1);
      const requested = input.throughDate ?? horizonEnd;
      const to = requested > horizonEnd ? horizonEnd : requested;

      if (to < from) {
        throw new BusinessRuleError(
          'schedule.range_inverted',
          'The generation range ends before it starts.',
          { details: { from, to: requested } },
        );
      }

      const empty: GenerateLessonsResult = {
        from,
        to,
        slotsConsidered: 0,
        candidates: 0,
        created: 0,
        skippedExisting: 0,
        skippedConflicting: 0,
        conflicts: [],
        clampedToHorizon: to !== requested,
        horizonWeeks,
      };

      const slots = await loadGenerableSlots(
        ctx,
        tx,
        { from, to },
        { branchId: input.branchId, groupId: input.groupId, slotId: input.slotId },
      );
      if (slots.length === 0) return empty;

      // ---- candidates ---------------------------------------------------
      const candidates: Array<{
        readonly slotId: string;
        readonly branchId: string;
        readonly groupId: string;
        readonly teacherId: string | null;
        readonly roomId: string | null;
        readonly subjectId: string | null;
        readonly lessonDate: DateOnly;
        readonly startsAt: Date;
        readonly endsAt: Date;
        readonly labels: { group: string };
      }> = [];

      for (const slot of slots) {
        // Intersect the requested range with the slot's own effective range and
        // the group's run dates; a slot cannot produce lessons before its group
        // starts or after it finishes.
        const groupStart = slot.group.startDate ? prismaDateToDateOnly(slot.group.startDate) : null;
        const groupEnd = slot.group.endDate ? prismaDateToDateOnly(slot.group.endDate) : null;

        const windowFrom = [from, slot.effectiveFrom, groupStart]
          .filter((value): value is DateOnly => value !== null)
          .reduce((a, b) => (a > b ? a : b));
        const windowTo = [to, slot.effectiveTo, groupEnd]
          .filter((value): value is DateOnly => value !== null)
          .reduce((a, b) => (a < b ? a : b));
        if (windowTo < windowFrom) continue;

        for (const date of datesMatchingWeekdays(windowFrom, windowTo, [slot.dayOfWeek], zone)) {
          candidates.push({
            slotId: slot.id,
            branchId: slot.branchId,
            groupId: slot.groupId,
            teacherId: slot.teacherId,
            roomId: slot.roomId,
            subjectId: slot.subjectId,
            lessonDate: date,
            startsAt: instantFor(date, slot.startMinute, zone),
            endsAt: instantFor(date, slot.endMinute, zone),
            labels: { group: slot.group.name },
          });
        }
      }

      if (candidates.length === 0) {
        return { ...empty, slotsConsidered: slots.length };
      }

      // ---- what is already booked, in ONE query -------------------------
      const groupIds = [...new Set(candidates.map((c) => c.groupId))];
      const teacherIds = [
        ...new Set(candidates.map((c) => c.teacherId).filter((id): id is string => id !== null)),
      ];
      const roomIds = [
        ...new Set(candidates.map((c) => c.roomId).filter((id): id is string => id !== null)),
      ];
      const { from: rangeStart, toExclusive: rangeEnd } = dayRangeToInstants(from, to, zone);

      const existingRows = await tx.lesson.findMany({
        where: {
          organizationId: ctx.organizationId,
          // Half-open overlap with the whole generation window.
          startsAt: { lt: rangeEnd },
          endsAt: { gt: rangeStart },
          OR: [
            { groupId: { in: groupIds } },
            ...(teacherIds.length > 0 ? [{ teacherId: { in: teacherIds } }] : []),
            ...(roomIds.length > 0 ? [{ roomId: { in: roomIds } }] : []),
          ],
        },
        select: {
          id: true,
          groupId: true,
          teacherId: true,
          roomId: true,
          startsAt: true,
          endsAt: true,
          status: true,
        },
      });

      // Cancelled lessons are deliberately NOT filtered out of the query: they
      // free their room (so the conflict index drops them) but they still occupy
      // the unique index, so re-generating must recognise them as already
      // existing rather than try to recreate them and resurrect a cancelled class.
      const existingKeys = new Set(existingRows.map((row) => lessonKey(row.groupId, row.startsAt)));
      const index = indexLessonsForConflicts(existingRows);

      const toCreate: Prisma.LessonCreateManyInput[] = [];
      const conflictSample: ScheduleConflict[] = [];
      let skippedExisting = 0;
      let skippedConflicting = 0;

      for (const candidate of candidates) {
        const key = lessonKey(candidate.groupId, candidate.startsAt);
        if (existingKeys.has(key)) {
          skippedExisting += 1;
          continue;
        }

        const conflicts = findLessonConflictsInIndex(candidate, index);
        if (conflicts.length > 0) {
          skippedConflicting += 1;
          for (const conflict of conflicts) {
            if (conflictSample.length < CONFLICT_SAMPLE_LIMIT) conflictSample.push(conflict);
          }
          continue;
        }

        toCreate.push({
          organizationId: ctx.organizationId,
          branchId: candidate.branchId,
          groupId: candidate.groupId,
          teacherId: candidate.teacherId,
          roomId: candidate.roomId,
          subjectId: candidate.subjectId,
          scheduleSlotId: candidate.slotId,
          lessonDate: dateOnlyToPrismaDate(candidate.lessonDate),
          startsAt: candidate.startsAt,
          endsAt: candidate.endsAt,
        });

        // Accepted candidates join the index so two patterns that (wrongly) share
        // a room cannot both be generated in one run.
        existingKeys.add(key);
        addToLessonConflictIndex(index, {
          id: `pending:${key}`,
          groupId: candidate.groupId,
          teacherId: candidate.teacherId,
          roomId: candidate.roomId,
          startsAt: candidate.startsAt,
          endsAt: candidate.endsAt,
        });
      }

      // `skipDuplicates` closes the race with a concurrent generation run: the
      // unique index turns the loser's rows into no-ops instead of an error.
      const inserted =
        toCreate.length > 0
          ? await tx.lesson.createMany({ data: toCreate, skipDuplicates: true })
          : { count: 0 };

      const result: GenerateLessonsResult = {
        from,
        to,
        slotsConsidered: slots.length,
        candidates: candidates.length,
        created: inserted.count,
        skippedExisting: skippedExisting + (toCreate.length - inserted.count),
        skippedConflicting,
        conflicts: conflictSample,
        clampedToHorizon: to !== requested,
        horizonWeeks,
      };

      await recordAudit(
        ctx,
        {
          action: AUDIT_ACTIONS.SCHEDULE_CHANGED,
          entityType: 'Lesson',
          branchId: input.branchId ?? null,
          summary: `Generated ${result.created} lesson(s) for ${from} to ${to} (${result.skippedExisting} already present, ${result.skippedConflicting} blocked)`,
          metadata: {
            from,
            to,
            slotsConsidered: result.slotsConsidered,
            candidates: result.candidates,
            created: result.created,
            skippedExisting: result.skippedExisting,
            skippedConflicting: result.skippedConflicting,
            clampedToHorizon: result.clampedToHorizon,
            groupId: input.groupId ?? null,
            slotId: input.slotId ?? null,
          },
        },
        tx,
      );

      if (result.skippedConflicting > 0) {
        logger.warn('scheduling.generation_conflicts', {
          requestId: ctx.requestId,
          organizationId: ctx.organizationId,
          from,
          to,
          skippedConflicting: result.skippedConflicting,
        });
      }

      return result;
    },
    { existing: db },
  );
}

// ---------------------------------------------------------------------------
// Ad-hoc lesson
// ---------------------------------------------------------------------------

export interface CreateAdHocLessonInput {
  readonly groupId: string;
  readonly lessonDate: DateOnly;
  readonly startMinute: number;
  readonly endMinute: number;
  readonly teacherId?: string | null;
  readonly roomId?: string | null;
  readonly subjectId?: string | null;
  readonly topic?: string | null;
  readonly lessonNumber?: number | null;
}

/**
 * A one-off lesson outside the pattern: a make-up class, an extra revision
 * session, a trial.
 *
 * Checked against BOTH levels. The instance check catches other lessons; the
 * pattern check catches a slot whose lessons have not been generated yet, which
 * is the case an instance-only check silently allows and is the reason the
 * schema's conflict note names both.
 */
export async function createAdHocLesson(
  ctx: AccessContext,
  input: CreateAdHocLessonInput,
  db?: Db,
): Promise<LessonDetail> {
  requirePermission(ctx, 'schedule.manage');

  // Serializable, not because money moves, but because the invariant has no
  // database constraint behind it: two administrators booking the same room at
  // the same instant would both read a clear check and both write under READ
  // COMMITTED. Write skew is the exact anomaly, and there is no unique index to
  // catch the loser.
  return withSerializableRetry(
    async (tx) => {
      assertMinuteWindow(input.startMinute, input.endMinute);

      const resources = await resolveResources(ctx, input, tx, 'lesson');
      assertGroupSchedulable(resources.group);

      const zone = resources.timezone;
      const startsAt = instantFor(input.lessonDate, input.startMinute, zone);
      const endsAt = instantFor(input.lessonDate, input.endMinute, zone);

      await assertSlotIsFree(
        ctx,
        tx,
        lessonAsSlotCandidate({
          groupId: input.groupId,
          teacherId: resources.teacherId,
          roomId: resources.roomId,
          dayOfWeek: weekdayOf(input.lessonDate, zone),
          startMinute: input.startMinute,
          endMinute: input.endMinute,
          onDate: input.lessonDate,
          labels: resources.labels,
        }),
      );

      await assertLessonIsFree(ctx, tx, {
        groupId: input.groupId,
        teacherId: resources.teacherId,
        roomId: resources.roomId,
        startsAt,
        endsAt,
        labels: resources.labels,
      });

      let created: { id: string };
      try {
        created = await tx.lesson.create({
          data: {
            organizationId: ctx.organizationId,
            branchId: resources.branchId,
            groupId: input.groupId,
            teacherId: resources.teacherId,
            roomId: resources.roomId,
            subjectId: resources.subjectId,
            lessonDate: dateOnlyToPrismaDate(input.lessonDate),
            startsAt,
            endsAt,
            topic: input.topic ?? null,
            lessonNumber: input.lessonNumber ?? null,
          },
          select: { id: true },
        });
      } catch (error) {
        // The (groupId, startsAt) unique index rejected a second lesson at the
        // same instant. Say so in a sentence an operator can act on.
        const code = (error as { code?: string }).code;
        if (code === 'P2002' || code === '23505') {
          throw new ConflictError(
            `${resources.group.name} already has a lesson starting at that time.`,
            { details: { groupId: input.groupId, startsAt: toIso(startsAt) } },
          );
        }
        throw error;
      }

      const detail = await loadLessonDetail(ctx, tx, created.id);

      await recordAudit(
        ctx,
        {
          action: AUDIT_ACTIONS.SCHEDULE_CHANGED,
          entityType: 'Lesson',
          entityId: detail.id,
          branchId: detail.branchId,
          summary: `Extra lesson added for ${detail.groupName} on ${detail.lessonDate} ${detail.startTime}–${detail.endTime}`,
          metadata: {
            groupId: detail.groupId,
            teacherId: detail.teacherId,
            roomId: detail.roomId,
            startsAt: toIso(startsAt),
            endsAt: toIso(endsAt),
          },
          timeline: {
            subjectType: 'GROUP',
            subjectId: detail.groupId,
            type: 'schedule.lesson.added',
            title: `Extra lesson on ${detail.lessonDate} at ${detail.startTime}`,
            description: input.topic ?? detail.roomName,
          },
        },
        tx,
      );

      return detail;
    },
    { existing: db },
  );
}

/** Load the lessons that could clash with a candidate, in one query, and check. */
async function assertLessonIsFree(
  ctx: AccessContext,
  db: Db,
  candidate: {
    readonly id?: string | null;
    readonly groupId: string;
    readonly teacherId: string | null;
    readonly roomId: string | null;
    readonly startsAt: Date;
    readonly endsAt: Date;
    readonly labels?: { group?: string | null; teacher?: string | null; room?: string | null };
  },
): Promise<void> {
  const rows = await db.lesson.findMany({
    where: {
      organizationId: ctx.organizationId,
      ...(candidate.id ? { id: { not: candidate.id } } : {}),
      status: { notIn: [...TIME_FREEING_LESSON_STATUSES] },
      // Half-open overlap, expressed in SQL so only real candidates are loaded.
      startsAt: { lt: candidate.endsAt },
      endsAt: { gt: candidate.startsAt },
      OR: [
        { groupId: candidate.groupId },
        ...(candidate.teacherId ? [{ teacherId: candidate.teacherId }] : []),
        ...(candidate.roomId ? [{ roomId: candidate.roomId }] : []),
      ],
    },
    select: {
      id: true,
      groupId: true,
      teacherId: true,
      roomId: true,
      startsAt: true,
      endsAt: true,
      status: true,
    },
  });

  const conflicts = findLessonConflictsInIndex(candidate, indexLessonsForConflicts(rows));
  if (conflicts.length > 0) throw new ScheduleConflictError(conflicts);
}

// ---------------------------------------------------------------------------
// Cancel
// ---------------------------------------------------------------------------

export async function cancelLesson(
  ctx: AccessContext,
  input: { readonly lessonId: string; readonly reason: string },
  db?: Db,
): Promise<{ id: string; status: LessonStatus; attendanceStatus: LessonAttendanceStatus }> {
  requirePermission(ctx, 'schedule.cancelLesson');

  if (input.reason.trim().length < 3) {
    throw new BusinessRuleError(
      'schedule.cancellation_reason_required',
      'A cancellation must record why the lesson is not happening.',
    );
  }

  return withTransaction(
    async (tx) => {
      const lesson = await tx.lesson.findFirst({
        where: { id: input.lessonId, ...scopeFilter(ctx) },
        select: {
          id: true,
          branchId: true,
          groupId: true,
          lessonDate: true,
          startsAt: true,
          status: true,
          attendanceStatus: true,
          group: { select: { name: true } },
        },
      });
      if (!lesson) throw new NotFoundError('Lesson', input.lessonId);

      if (lesson.status === 'CANCELLED') {
        throw new StateInvalidError('lesson', 'already cancelled', 'cancelled');
      }
      if (lesson.attendanceStatus === 'SUBMITTED' || lesson.attendanceStatus === 'APPROVED') {
        // A lesson whose register has been signed off demonstrably happened.
        // Un-happening it would contradict attendance that students and parents
        // have already been shown; a correction is the right instrument.
        throw new StateInvalidError(
          'lesson',
          'already registered',
          'cancelled',
          'This lesson already has a submitted attendance register, so it cannot be cancelled. Correct the attendance instead.',
        );
      }

      await tx.lesson.update({
        where: { id: lesson.id },
        data: {
          status: 'CANCELLED',
          cancellationReason: input.reason,
          // NOT_REQUIRED takes the lesson off the "registers outstanding"
          // worklist and out of the attendance denominator: a class that did not
          // happen must not count against a student's attendance rate.
          attendanceStatus: 'NOT_REQUIRED',
        },
      });

      await recordAudit(
        ctx,
        {
          action: AUDIT_ACTIONS.LESSON_CANCELLED,
          entityType: 'Lesson',
          entityId: lesson.id,
          branchId: lesson.branchId,
          summary: `Lesson cancelled for ${lesson.group.name} on ${prismaDateToDateOnly(lesson.lessonDate)}`,
          reason: input.reason,
          severity: 'NOTICE',
          metadata: { startsAt: toIso(lesson.startsAt), previousStatus: lesson.status },
          timeline: {
            subjectType: 'GROUP',
            subjectId: lesson.groupId,
            type: 'schedule.lesson.cancelled',
            title: `Lesson on ${prismaDateToDateOnly(lesson.lessonDate)} cancelled`,
            description: input.reason,
          },
        },
        tx,
      );

      return { id: lesson.id, status: 'CANCELLED', attendanceStatus: 'NOT_REQUIRED' };
    },
    { existing: db },
  );
}

// ---------------------------------------------------------------------------
// Reschedule
// ---------------------------------------------------------------------------

export interface RescheduleLessonInput {
  readonly lessonId: string;
  /** Any field left out keeps its current value. */
  readonly lessonDate?: DateOnly;
  readonly startMinute?: number;
  readonly endMinute?: number;
  readonly teacherId?: string | null;
  readonly roomId?: string | null;
  readonly reason: string;
}

/**
 * Move a lesson, keeping its identity.
 *
 * The same row moves rather than being replaced, because attendance, homework and
 * grades reference `lessonId`; replacing it would orphan them. The change is
 * audited field by field, so "why is Tuesday's class at 14:00 now" has an answer.
 */
export async function rescheduleLesson(
  ctx: AccessContext,
  input: RescheduleLessonInput,
  db?: Db,
): Promise<LessonDetail> {
  requirePermission(ctx, 'schedule.cancelLesson');

  if (input.reason.trim().length < 3) {
    throw new BusinessRuleError(
      'schedule.reschedule_reason_required',
      'A reschedule must record why the lesson is moving.',
    );
  }

  // Serializable, not because money moves, but because the invariant has no
  // database constraint behind it: two administrators booking the same room at
  // the same instant would both read a clear check and both write under READ
  // COMMITTED. Write skew is the exact anomaly, and there is no unique index to
  // catch the loser.
  return withSerializableRetry(
    async (tx) => {
      const lesson = await tx.lesson.findFirst({
        where: { id: input.lessonId, ...scopeFilter(ctx) },
        select: {
          id: true,
          branchId: true,
          groupId: true,
          teacherId: true,
          roomId: true,
          subjectId: true,
          scheduleSlotId: true,
          lessonDate: true,
          startsAt: true,
          endsAt: true,
          status: true,
          attendanceStatus: true,
        },
      });
      if (!lesson) throw new NotFoundError('Lesson', input.lessonId);

      if (lesson.status === 'CANCELLED') {
        throw new StateInvalidError('lesson', 'cancelled', 'rescheduled');
      }
      if (lesson.attendanceStatus === 'SUBMITTED' || lesson.attendanceStatus === 'APPROVED') {
        throw new StateInvalidError(
          'lesson',
          'already registered',
          'rescheduled',
          'This lesson already has a submitted attendance register and cannot be moved.',
        );
      }

      const teacherId = input.teacherId === undefined ? lesson.teacherId : input.teacherId;
      const roomId = input.roomId === undefined ? lesson.roomId : input.roomId;

      const resources = await resolveResources(
        ctx,
        { groupId: lesson.groupId, teacherId, roomId, subjectId: lesson.subjectId },
        tx,
        'lesson',
      );
      const zone = resources.timezone;

      const lessonDate = input.lessonDate ?? prismaDateToDateOnly(lesson.lessonDate);
      const startMinute = input.startMinute ?? instantToWallClockMinute(lesson.startsAt, zone);
      const endMinute = input.endMinute ?? instantToWallClockMinute(lesson.endsAt, zone);
      assertMinuteWindow(startMinute, endMinute);

      const startsAt = instantFor(lessonDate, startMinute, zone);
      const endsAt = instantFor(lessonDate, endMinute, zone);

      await assertSlotIsFree(
        ctx,
        tx,
        lessonAsSlotCandidate({
          groupId: lesson.groupId,
          teacherId,
          roomId,
          dayOfWeek: weekdayOf(lessonDate, zone),
          startMinute,
          endMinute,
          onDate: lessonDate,
          labels: resources.labels,
        }),
        // The lesson's own pattern still reserves the hour it came from, and a
        // small move inside that window would otherwise clash with the very slot
        // this lesson is an instance of.
        lesson.scheduleSlotId,
      );

      await assertLessonIsFree(ctx, tx, {
        id: lesson.id,
        groupId: lesson.groupId,
        teacherId,
        roomId,
        startsAt,
        endsAt,
        labels: resources.labels,
      });

      await tx.lesson.update({
        where: { id: lesson.id },
        data: {
          lessonDate: dateOnlyToPrismaDate(lessonDate),
          startsAt,
          endsAt,
          teacherId,
          roomId,
        },
      });

      const detail = await loadLessonDetail(ctx, tx, lesson.id);

      await recordAudit(
        ctx,
        {
          action: AUDIT_ACTIONS.LESSON_RESCHEDULED,
          entityType: 'Lesson',
          entityId: lesson.id,
          branchId: lesson.branchId,
          summary: `Lesson for ${detail.groupName} moved to ${lessonDate} ${formatWallClock(startMinute)}`,
          reason: input.reason,
          severity: 'NOTICE',
          changes: diffFields(
            {
              lessonDate: prismaDateToDateOnly(lesson.lessonDate),
              startsAt: lesson.startsAt,
              endsAt: lesson.endsAt,
              teacherId: lesson.teacherId,
              roomId: lesson.roomId,
            },
            {
              lessonDate,
              startsAt,
              endsAt,
              teacherId,
              roomId,
            },
          ),
          timeline: {
            subjectType: 'GROUP',
            subjectId: lesson.groupId,
            type: 'schedule.lesson.rescheduled',
            title: `Lesson moved to ${lessonDate} at ${formatWallClock(startMinute)}`,
            description: input.reason,
          },
        },
        tx,
      );

      return detail;
    },
    { existing: db },
  );
}

// ---------------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------------

const LESSON_SELECT = {
  id: true,
  branchId: true,
  groupId: true,
  teacherId: true,
  roomId: true,
  subjectId: true,
  scheduleSlotId: true,
  lessonDate: true,
  startsAt: true,
  endsAt: true,
  topic: true,
  lessonNumber: true,
  status: true,
  cancellationReason: true,
  attendanceStatus: true,
  attendanceSubmittedAt: true,
  group: { select: { name: true, code: true } },
  room: { select: { name: true } },
  subject: { select: { name: true } },
  teacher: {
    select: { employee: { select: { user: { select: { firstName: true, lastName: true } } } } },
  },
  _count: { select: { attendanceRecords: true } },
} satisfies Prisma.LessonSelect;

type LessonRow = Prisma.LessonGetPayload<{ select: typeof LESSON_SELECT }>;

export interface LessonSummary {
  readonly id: string;
  readonly branchId: string;
  readonly groupId: string;
  readonly groupName: string;
  readonly groupCode: string;
  readonly teacherId: string | null;
  readonly teacherName: string | null;
  readonly roomId: string | null;
  readonly roomName: string | null;
  readonly subjectId: string | null;
  readonly subjectName: string | null;
  readonly scheduleSlotId: string | null;
  readonly lessonDate: DateOnly;
  readonly startsAt: Date;
  readonly endsAt: Date;
  /** `HH:MM` in the branch timezone. */
  readonly startTime: string;
  readonly endTime: string;
  readonly durationMinutes: number;
  readonly topic: string | null;
  readonly lessonNumber: number | null;
  readonly status: LessonStatus;
  readonly cancellationReason: string | null;
  readonly attendanceStatus: LessonAttendanceStatus;
  readonly registerSubmitted: boolean;
  readonly markedCount: number;
}

export interface LessonDetail extends LessonSummary {
  /** Students whose enrollment was open on the lesson date. */
  readonly enrolledCount: number;
}

function toLessonSummary(row: LessonRow, zone: TimeZone): LessonSummary {
  const teacherUser = row.teacher?.employee.user;
  return {
    id: row.id,
    branchId: row.branchId,
    groupId: row.groupId,
    groupName: row.group.name,
    groupCode: row.group.code,
    teacherId: row.teacherId,
    teacherName: teacherUser ? `${teacherUser.firstName} ${teacherUser.lastName}` : null,
    roomId: row.roomId,
    roomName: row.room?.name ?? null,
    subjectId: row.subjectId,
    subjectName: row.subject?.name ?? null,
    scheduleSlotId: row.scheduleSlotId,
    lessonDate: prismaDateToDateOnly(row.lessonDate),
    startsAt: row.startsAt,
    endsAt: row.endsAt,
    startTime: formatTime(row.startsAt, zone),
    endTime: formatTime(row.endsAt, zone),
    durationMinutes: Math.round((row.endsAt.getTime() - row.startsAt.getTime()) / 60_000),
    topic: row.topic,
    lessonNumber: row.lessonNumber,
    status: row.status,
    cancellationReason: row.cancellationReason,
    attendanceStatus: row.attendanceStatus,
    registerSubmitted:
      row.attendanceStatus === 'SUBMITTED' || row.attendanceStatus === 'APPROVED',
    markedCount: row._count.attendanceRecords,
  };
}

/**
 * One lesson with its roster size.
 *
 * `extraWhere` carries a reader's SELF narrowing. Write paths pass nothing: a
 * teacher who has just created a lesson must be able to read back what they made,
 * and the write already established that they may.
 */
async function loadLessonDetail(
  ctx: AccessContext,
  db: Db,
  lessonId: string,
  extraWhere: Prisma.LessonWhereInput = {},
): Promise<LessonDetail> {
  const row = await db.lesson.findFirst({
    where: { id: lessonId, ...scopeFilter(ctx), ...extraWhere },
    select: LESSON_SELECT,
  });
  if (!row) throw new NotFoundError('Lesson', lessonId);

  const settings = await getSettings(
    ['timezone'],
    { organizationId: ctx.organizationId, branchId: row.branchId },
    db,
  );

  const enrolledCount = await db.enrollment.count({
    where: {
      groupId: row.groupId,
      startDate: { lte: row.lessonDate },
      OR: [{ endDate: null }, { endDate: { gte: row.lessonDate } }],
      student: { deletedAt: null },
    },
  });

  return { ...toLessonSummary(row, settings.timezone), enrolledCount };
}

export interface ListLessonsFilters {
  readonly from?: DateOnly | null;
  readonly to?: DateOnly | null;
  readonly groupId?: string | null;
  readonly teacherId?: string | null;
  readonly roomId?: string | null;
  readonly branchId?: string | null;
  readonly status?: LessonStatus | null;
  readonly attendanceStatus?: LessonAttendanceStatus | null;
  readonly includeCancelled?: boolean;
  readonly page?: number;
  readonly pageSize?: number;
}

export async function listLessons(
  ctx: AccessContext,
  filters: ListLessonsFilters = {},
  db: Db = prisma,
): Promise<{ rows: LessonSummary[]; total: number; page: number; pageSize: number }> {
  requirePermission(ctx, 'schedule.view');

  const page = Math.max(1, filters.page ?? 1);
  const pageSize = Math.min(100, Math.max(1, filters.pageSize ?? 50));

  const settings = await getSettings(
    ['timezone'],
    { organizationId: ctx.organizationId, branchId: filters.branchId ?? null },
    db,
  );

  const where: Prisma.LessonWhereInput = {
    ...(composeReadFilter(ctx, {
      selfFilter: teacherLessonFilter(ctx),
      escapeHatch: 'schedule.viewAll',
    }) as object),
    ...(filters.branchId ? { branchId: filters.branchId } : {}),
    ...(filters.groupId ? { groupId: filters.groupId } : {}),
    ...(filters.teacherId ? { teacherId: filters.teacherId } : {}),
    ...(filters.roomId ? { roomId: filters.roomId } : {}),
    ...(filters.status ? { status: filters.status } : {}),
    ...(filters.attendanceStatus ? { attendanceStatus: filters.attendanceStatus } : {}),
    ...(filters.status || filters.includeCancelled ? {} : { status: { not: 'CANCELLED' } }),
    // Filtered on the indexed calendar column rather than on the instants, which
    // is what makes "this week's lessons" a range scan.
    ...(filters.from || filters.to
      ? {
          lessonDate: {
            ...(filters.from ? { gte: dateOnlyToPrismaDate(filters.from) } : {}),
            ...(filters.to ? { lte: dateOnlyToPrismaDate(filters.to) } : {}),
          },
        }
      : {}),
  };

  const [rows, total] = await Promise.all([
    db.lesson.findMany({
      where,
      orderBy: [{ lessonDate: 'asc' }, { startsAt: 'asc' }],
      skip: (page - 1) * pageSize,
      take: pageSize,
      select: LESSON_SELECT,
    }),
    db.lesson.count({ where }),
  ]);

  return {
    rows: rows.map((row) => toLessonSummary(row, settings.timezone)),
    total,
    page,
    pageSize,
  };
}

/** One lesson, with the roster size the register will show. */
export async function getLesson(
  ctx: AccessContext,
  lessonId: string,
  db: Db = prisma,
): Promise<LessonDetail> {
  requirePermission(ctx, 'schedule.view');

  // Tenancy, branch and "is this mine" all live in the SAME `where` as the id.
  // Fetching first and checking after would confirm the existence of another
  // branch's lesson to anyone who can guess an id.
  return loadLessonDetail(ctx, db, lessonId, {
    ...(composeReadFilter(ctx, {
      selfFilter: teacherLessonFilter(ctx),
      escapeHatch: 'schedule.viewAll',
    }) as object),
  });
}

// ---------------------------------------------------------------------------
// The mobile teacher flow
// ---------------------------------------------------------------------------

export interface TeacherDayLesson {
  readonly id: string;
  readonly groupId: string;
  readonly groupName: string;
  readonly groupCode: string;
  readonly subjectName: string | null;
  readonly roomName: string | null;
  readonly startsAt: Date;
  readonly endsAt: Date;
  /** Pre-formatted for the phone screen, in the branch timezone. */
  readonly startTime: string;
  readonly endTime: string;
  readonly status: LessonStatus;
  readonly attendanceStatus: LessonAttendanceStatus;
  readonly registerSubmitted: boolean;
  readonly enrolledCount: number;
  readonly markedCount: number;
  readonly topic: string | null;
}

export interface TeacherDay {
  readonly date: DateOnly;
  readonly timezone: TimeZone;
  readonly teacherId: string;
  readonly lessons: readonly TeacherDayLesson[];
}

/**
 * The first screen a teacher sees on a phone: today's classes, with enough on
 * each card to decide what to tap.
 *
 * TWO queries, always. The lessons come back in one; the roster sizes come back
 * in one grouped count keyed by group, because "how many students are enrolled on
 * this date" is a dated question the relation count cannot express — and asking it
 * per lesson would be the N+1 this endpoint can least afford.
 */
export async function getTodaysLessonsForTeacher(
  ctx: AccessContext,
  input: { readonly date?: DateOnly; readonly teacherId?: string } = {},
  db: Db = prisma,
): Promise<TeacherDay> {
  requirePermission(ctx, 'schedule.view');

  const ownTeacherId = ctx.self.teacherId;
  const mayViewOthers = ctx.isSystem || can(ctx, 'schedule.viewAll');

  if (input.teacherId && input.teacherId !== ownTeacherId && !mayViewOthers) {
    throw new ForbiddenError("You can only open your own timetable.");
  }
  const teacherId = input.teacherId ?? ownTeacherId;
  if (!teacherId) {
    throw new ForbiddenError('This account is not linked to a teacher.');
  }

  const settings = await getSettings(['timezone'], { organizationId: ctx.organizationId }, db);
  const date = input.date ?? todayIn(settings.timezone);
  const on = dateOnlyToPrismaDate(date);

  const lessons = await db.lesson.findMany({
    where: {
      ...scopeFilter(ctx),
      lessonDate: on,
      // A lesson moved to another day is no longer part of this day; a cancelled
      // one stays visible so the teacher knows not to turn up for it.
      status: { not: 'RESCHEDULED' },
      OR: [
        { teacherId },
        { group: { teacherAssignments: { some: { teacherId, endDate: null } } } },
      ],
    },
    orderBy: { startsAt: 'asc' },
    select: {
      id: true,
      groupId: true,
      startsAt: true,
      endsAt: true,
      status: true,
      attendanceStatus: true,
      topic: true,
      group: { select: { name: true, code: true } },
      room: { select: { name: true } },
      subject: { select: { name: true } },
      _count: { select: { attendanceRecords: true } },
    },
  });

  if (lessons.length === 0) {
    return { date, timezone: settings.timezone, teacherId, lessons: [] };
  }

  const rosterSizes = await db.enrollment.groupBy({
    by: ['groupId'],
    where: {
      groupId: { in: [...new Set(lessons.map((lesson) => lesson.groupId))] },
      startDate: { lte: on },
      OR: [{ endDate: null }, { endDate: { gte: on } }],
      student: { deletedAt: null },
    },
    _count: { _all: true },
  });
  const enrolledByGroup = new Map(rosterSizes.map((row) => [row.groupId, row._count._all]));

  return {
    date,
    timezone: settings.timezone,
    teacherId,
    lessons: lessons.map((lesson) => ({
      id: lesson.id,
      groupId: lesson.groupId,
      groupName: lesson.group.name,
      groupCode: lesson.group.code,
      subjectName: lesson.subject?.name ?? null,
      roomName: lesson.room?.name ?? null,
      startsAt: lesson.startsAt,
      endsAt: lesson.endsAt,
      startTime: formatTime(lesson.startsAt, settings.timezone),
      endTime: formatTime(lesson.endsAt, settings.timezone),
      status: lesson.status,
      attendanceStatus: lesson.attendanceStatus,
      registerSubmitted:
        lesson.attendanceStatus === 'SUBMITTED' || lesson.attendanceStatus === 'APPROVED',
      enrolledCount: enrolledByGroup.get(lesson.groupId) ?? 0,
      markedCount: lesson._count.attendanceRecords,
      topic: lesson.topic,
    })),
  };
}
